# Generated by Django 5.0.4 on 2024-04-14 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw4_app', '0002_client_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
